### ISSUE TITLE
Ability to select fields which are visible on report's print page

### ISSUE THREAD

**Issue by Gaya** [Gaya/thyme#102]
Right now the printed / pdf version of a report shows all the fields in the detailed view. It would be nice if we could hide / show columns for print / pdf.

**Comment by Scoombe** [comment]
@Gaya I'd like to have a look at this, would that be alright? 

Anything I'll need to know before looking at it? Cheers.

**Comment by Gaya** [comment]
Yeah, this would be a good thing for you to set up. I am going to make some detailed ideas in here as soon as I get the time. Thank you for volunteering to take on this task

**Comment by Scoombe** [comment]
@Gaya where is the printed version? Is this just a print preview from your browser? or is it a button or something?

**Comment by Scoombe** [comment]
@Gaya  is this just a button on the detailed view columns to hide or show these options in the print preview?

**Comment by Scoombe** [comment]
@Gaya something like this?
![image](https://user-images.githubusercontent.com/6514233/46071336-b236b980-c177-11e8-82aa-ddf839b0cd99.png)
