### ISSUE TITLE
Have a button to return to the main page

### ISSUE THREAD

**Issue by Scoombe** [Gaya/thyme#106]
Once you click on use time it's hard to return to the home page.

**Comment by Gaya** [comment]
@Scoombe do you mean to the website? It would be a good idea to add it to the menu indeed

**Comment by Scoombe** [comment]
I mean this page once you are in the /thyme part of the website

![image](https://user-images.githubusercontent.com/6514233/46070263-39366280-c175-11e8-919b-13a723bb499c.png)

Maybe put the button here? 

![image](https://user-images.githubusercontent.com/6514233/46070318-608d2f80-c175-11e8-9d0e-3585676b7a50.png)
