### ISSUE TITLE
The filter button on the report page seems to be broken.

### ISSUE THREAD

**Issue by Scoombe** [Gaya/thyme#108]

**Comment by Scoombe** [comment]
When I select something to remove or add it toggles more than just the one I clicked on.

**Comment by Scoombe** [comment]
This is happening on the reports page 
![image](https://user-images.githubusercontent.com/6514233/46071500-0f326f80-c178-11e8-939d-ef787d99dc61.png)

**Comment by Gaya** [comment]
Nice find. Will fix ASAP
