### ISSUE TITLE
Add yarn caching for travis ci builds?

### ISSUE THREAD

**Issue by Scoombe** [Gaya/thyme#140]
Will lead to faster travis CI checks.

**Comment by Scoombe** [comment]
@Gaya seeing any improvements at all?

**Comment by Gaya** [comment]
Didn't really see that much difference, but the builds weren't that bad anyway before. Guessing it does help a bit

**Comment by Gaya** [comment]
I took a closer look and the only thing slowing Travis down is the build right now. I removed this step as Netlify will do it too anyway, which also has to succeed. This will make Travis very fast.
