### ISSUE TITLE
Rounding not working.

### ISSUE THREAD

**Issue by Scoombe** [Gaya/thyme#148]
I don't think that the rounding is working. I can't get the duration to round at all. When is the rounding meant to be happening?

**Comment by Gaya** [comment]
What is not working for you? Please notice the "new" entries don't get rounding before they're added. It might be a good idea to enable rounding when the clock is not "running" though.

**Comment by Scoombe** [comment]
My bad, it is working, I was just expecting the rounding on different fields.
