### ISSUE TITLE
Improve UI of logging hours and start tracking

### ISSUE THREAD

**Issue by Gaya** [Gaya/thyme#34]
These icons are not clear enough and should be revised.

![image](https://user-images.githubusercontent.com/970834/39133250-0cb21dac-4714-11e8-9672-f12a51df8cca.png)

**Comment by Scoombe** [comment]
@Gaya  Looks good I like them. Did you create them?

**Comment by Gaya** [comment]
@Scoombe I used React Semantic UI for the new buttons.
