### ISSUE TITLE
Time issue

### ISSUE THREAD

**Issue by barrykooij** [Gaya/thyme#35]
![image](https://user-images.githubusercontent.com/2846594/39174114-0a5c3e46-47a7-11e8-9b12-be3c32cdd2d9.png)

**Comment by Gaya** [comment]
Thanks for filling this issue. Will take a better look at formatting time.

**Comment by Scoombe** [comment]
How is this error produced?

**Comment by Gaya** [comment]
@Scoombe I will have to dig into this one. I'll try and get more information about this one tomorrow.

**Comment by Gaya** [comment]
Apparently it has to do with the pesky floating point issue in JavaScript. http://floating-point-gui.de/

This is probably best solved by rounding the number during the format in https://github.com/Gaya/thyme/blob/master/src/core/thyme.js#L28
