### ISSUE TITLE
Ability to round start and end times

### ISSUE THREAD

**Issue by Gaya** [Gaya/thyme#36]
For administrational purposes. It would be could if the user is allowed to setup rounding of start and end times. For example: round at 5 minutes, making the start and end time always rounded at 5 minutes instead of on the minute.

Allow for rounding normal, up or down. And picking the increments of 5 minutes, 10 minutes, 15 minutes, 30 minutes, an hour, or a custom amount.

**Comment by Scoombe** [comment]
I've had a look at the settings page and using redux, I could use some help though. I'll put in a pull request

**Comment by Gaya** [comment]
Another user with this request. https://twitter.com/javorszky/status/1025459459060101121

**Comment by Scoombe** [comment]
@Gaya I was starting to have another look at noticed the working on label

**Comment by Gaya** [comment]
@Scoombe I didn't actually start this one yet. You can have it and I'll keep the label. Thought you might have stopped because you closed the PR

**Comment by Scoombe** [comment]
@Gaya I started after you posted the twitter link, I think I'm pretty close this time. Just need to figure out the best place to the rounding, I've put a button next to the rounding?

**Comment by Gaya** [comment]
@Scoombe Good to hear! If you can make a PR and post some screenshots there we could discuss it further over there.

**Comment by Gaya** [comment]
It's way more complex than I initially thought. Simply rounding the start and end times would not really solve the problem.

We'd want to round the actual duration of an item or everything on a report. I am going to open a PR which will take a stab at this.

**Comment by Scoombe** [comment]
@Gaya you're thinking of doing the rounding on all of the items, when one of the times changes? 

Sounds good, I'll be interested to see what you come up with.
