### ISSUE TITLE
website is broken

### ISSUE THREAD

**Issue by Scoombe** [Gaya/thyme#57]
https://usethyme.com is down for the moment.

**Comment by Gaya** [comment]
Is this related to #58 ?

**Comment by Scoombe** [comment]
Getting a different error message.
![image](https://user-images.githubusercontent.com/6514233/39957322-11bf4084-55e9-11e8-976e-a2b5b3b942c7.png)

**Comment by Gaya** [comment]
Ah, makes sense! Fixed it in #61

**Comment by Scoombe** [comment]
Fixed! Nice one
