### ISSUE TITLE
Error when running migrations.

### ISSUE THREAD

**Issue by Scoombe** [Gaya/thyme#58]
I'm getting the error

TypeError: Cannot read property 'split' of undefined

![image](https://user-images.githubusercontent.com/6514233/39932119-3a38d4b0-5537-11e8-8ba2-f3a01c992502.png)

**Comment by Gaya** [comment]
Would you mind sharing your localStorage data if this persists so I can debug?

**Comment by Scoombe** [comment]
I won't be able to look at this until Monday.

**Comment by Scoombe** [comment]
This is still happening

**Comment by Scoombe** [comment]
Hi, I have looked at the changes you made yesterday in #62 , this now works. Thanks.

**Comment by Gaya** [comment]
Great! Thanks for checking it out and reporting. I will close this now.
