### ISSUE TITLE
Make it possible to select the date for end time as well

### ISSUE THREAD

**Issue by Gaya** [Gaya/thyme#75]
Right now selecting an end date is not possible. When people working nights would use it it can become problematic.
Allow for end dates to be selected just as start dates.

**Comment by Alfreddatui** [comment]
can I work on this?

**Comment by Gaya** [comment]
Sure, if you'd like to. I'll put the label "currently working on" if you want to start

**Comment by Alfreddatui** [comment]
yep, please put the label

**Comment by Alfreddatui** [comment]
Hey @Gaya 

I notice other bug, can you raise an issue for it.

<img width="1427" alt="screen shot 2018-10-02 at 22 50 12" src="https://user-images.githubusercontent.com/25166400/46356576-9a8a9400-c695-11e8-88fa-47bb086cd87e.png">

I will try to make PR for this issue, and after that will try to fix that

**Comment by Gaya** [comment]
@Alfreddatui That's weird! How did you get this rendering? This should not happen 😅

**Comment by Gaya** [comment]
@Alfreddatui any progress on this issue? I would really like to fix this, but if you're already on it then I'll let you have it

**Comment by Alfreddatui** [comment]
Hi @Gaya, I am sorry, currently I am occupied with my school project.
If it is urgent, go ahead to take it. But if it is not, I will be more than happy to fix this issue #75

**Comment by Gaya** [comment]
Thanks for the update. I won't be able to start this task until next week, but I'll definitely want to look at it by then. I'll let you know when I start.

**Comment by Scoombe** [comment]
@Gaya I had a go at this.

**Comment by Gaya** [comment]
Closed, thanks you @Scoombe !

**Comment by Scoombe** [comment]
@Gaya looks good
