### ISSUE TITLE
Add seconds counter in timesheet duration field when tracking time

### ISSUE THREAD

**Issue by ThomasRoest** [Gaya/thyme#82]
a suggestion to include seconds in the duration field on timesheets page --> 00:00:00 

This could could be added to provide some better immediate visual feedback that the tracking has started, the 00:00 duration was a bit confusing at first since it only shows hour/minutes.

**Comment by Gaya** [comment]
Sorry I totally missed this issue! Adding seconds is actually something I thought about earlier. I will test to see the effects of this.

I think I will only add the seconds on the "running" timer though.

**Comment by Gaya** [comment]
Will look like this.

![image](https://user-images.githubusercontent.com/970834/43661121-58c9227e-9761-11e8-96cf-48c381a6ee8d.png)

Will create a PR for it

**Comment by Gaya** [comment]
Merged. Thanks for the suggestions again @ThomasRoest
